title: JCJK制服至上的电波主页 (〃▽〃) ♡⌒✿ (灬º‿º灬)
description: 用 GitHub Pages + Jekyll（minima 主题）搭建
theme: minima
locale: zh-CN

minima:
  skin: classic
  date_format: "%Y年%-m月%-d日"

sass:
  style: compressed

header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10                 # 每页 10 篇（测试想强制出现分页可暂时改成 2）
paginate_path: "/page:num/"  # /page2/ /page3/ ...
